(** SHARED DEFINITIONS — for [transfer].

    Source contract: examples.bank_transfer.contract:transfer_contract
    Generated by specsaver.lower (layered v3). *)

From iris.proofmode Require Import proofmode.
From iris.base_logic.lib Require Import gen_heap.
Require Import SnakeletExnLang SnakeletExnWp.
Require Import SpecPrelude.

Section gen_transfer.
Context `{FC : FunCtx}.

Definition store_loc : loc := Loc 1%positive.
Definition trace_loc : loc := Loc 2%positive.

Definition row_of (balance : Z) (currency : string) : sn_val :=
  LitDict [(LitString "balance", LitInt balance);
           (LitString "currency", LitString currency)].

Definition row_inv (v : sn_val) : Prop :=
  exists balance currency,
    v = (row_of (balance) (currency)) /\ (balance >= 0)%Z.

Fixpoint store_inv (kvs : list (sn_val * sn_val)) : Prop :=
  match kvs with
  | [] => True
  | (_, v) :: rest => row_inv v /\ store_inv rest
  end.

Definition gen_pre (sigma : sn_state) (vs : list sn_val) : Prop :=
  exists source_id target_id order amount store_d balance_source_id currency_source_id balance_target_id currency_target_id,
    vs = [LitString source_id; LitString target_id; LitString order; LitInt amount] /\
    sigma !! store_loc = Some (LitDict store_d) /\
    dict_lookup_str source_id store_d = Some (row_of (balance_source_id) (currency_source_id)) /\
    dict_lookup_str target_id store_d = Some (row_of (balance_target_id) (currency_target_id)) /\
    (amount > 0)%Z /\ (source_id <> target_id) /\ (((currency_source_id <> currency_target_id) \/ (balance_source_id >= amount)%Z) /\ ((currency_source_id = currency_target_id))).

Definition gen_post (sigma : sn_state) (vs : list sn_val)
    (r : Result) (ups : cell_updates) : Prop :=
  exists source_id target_id order amount store_d balance_source_id currency_source_id balance_target_id currency_target_id,
    vs = [LitString source_id; LitString target_id; LitString order; LitInt amount] /\
    sigma !! store_loc = Some (LitDict store_d) /\
    dict_lookup_str source_id store_d = Some (row_of (balance_source_id) (currency_source_id)) /\
    dict_lookup_str target_id store_d = Some (row_of (balance_target_id) (currency_target_id)) /\
    r = RVal (LitInt balance_source_id) /\
    ups = [(store_loc, LitDict (dict_insert_str target_id (row_of (balance_target_id + amount) (currency_target_id)) (dict_insert_str source_id (row_of (balance_source_id - amount) (currency_source_id)) store_d)))].

Definition gen_exc0_pre (sigma : sn_state) (vs : list sn_val) : Prop :=
  exists source_id target_id order amount store_d balance_source_id currency_source_id balance_target_id currency_target_id,
    vs = [LitString source_id; LitString target_id; LitString order; LitInt amount] /\
    sigma !! store_loc = Some (LitDict store_d) /\
    dict_lookup_str source_id store_d = Some (row_of (balance_source_id) (currency_source_id)) /\
    dict_lookup_str target_id store_d = Some (row_of (balance_target_id) (currency_target_id)) /\
    (currency_source_id = currency_target_id) /\
    (balance_source_id < amount)%Z.

Definition gen_exc0_post (sigma : sn_state) (vs : list sn_val)
    (r : Result) (ups : cell_updates) : Prop :=
  exists source_id target_id order amount store_d balance_source_id currency_source_id balance_target_id currency_target_id,
    vs = [LitString source_id; LitString target_id; LitString order; LitInt amount] /\
    sigma !! store_loc = Some (LitDict store_d) /\
    dict_lookup_str source_id store_d = Some (row_of (balance_source_id) (currency_source_id)) /\
    dict_lookup_str target_id store_d = Some (row_of (balance_target_id) (currency_target_id)) /\
    r = RExn "InsufficientFundsError" (LitTuple [LitString source_id; LitInt amount]) /\ ups = [].

Definition gen_exc1_pre (sigma : sn_state) (vs : list sn_val) : Prop :=
  exists source_id target_id order amount store_d balance_source_id currency_source_id balance_target_id currency_target_id,
    vs = [LitString source_id; LitString target_id; LitString order; LitInt amount] /\
    sigma !! store_loc = Some (LitDict store_d) /\
    dict_lookup_str source_id store_d = Some (row_of (balance_source_id) (currency_source_id)) /\
    dict_lookup_str target_id store_d = Some (row_of (balance_target_id) (currency_target_id)) /\
    (currency_source_id <> currency_target_id).

Definition gen_exc1_post (sigma : sn_state) (vs : list sn_val)
    (r : Result) (ups : cell_updates) : Prop :=
  exists source_id target_id order amount store_d balance_source_id currency_source_id balance_target_id currency_target_id,
    vs = [LitString source_id; LitString target_id; LitString order; LitInt amount] /\
    sigma !! store_loc = Some (LitDict store_d) /\
    dict_lookup_str source_id store_d = Some (row_of (balance_source_id) (currency_source_id)) /\
    dict_lookup_str target_id store_d = Some (row_of (balance_target_id) (currency_target_id)) /\
    r = RExn "CurrencyMismatchError" (LitTuple [LitString source_id; LitString target_id]) /\ ups = [].

Definition gen_table (f : string) : option fun_entry :=
  if String.eqb f "transfer" then Some (FunSpecS gen_pre gen_post)
  else if String.eqb f "transfer_exc0" then
  Some (FunSpecS gen_exc0_pre gen_exc0_post)
  else if String.eqb f "transfer_exc1" then
  Some (FunSpecS gen_exc1_pre gen_exc1_post)
  else None.

Lemma store_inv_lookup : forall store_d k row,
  store_inv store_d ->
  dict_lookup_str k store_d = Some row ->
  row_inv row.
Proof.
  induction store_d as [|kv rest IH]; intros k row Hinv Hlook; simpl in *.
  - discriminate.
  - destruct kv as [k0 v0].
    destruct Hinv as [Hfst Hrest].
    destruct k0 as [| | s | | | | | | | |]; simpl in *;
      try (apply (IH k row Hrest Hlook)).
    destruct (String.eqb k s) eqn:E.
    + injection Hlook as Hlook. subst v0. exact Hfst.
    + apply (IH k row Hrest Hlook).
Qed.

Lemma gen_table_total_pure : forall f pre post vs,
  gen_table f = Some (FunSpec pre post) ->
  pre vs -> exists v, post vs v.
Proof.
  intros f pre post vs Hfe _. unfold gen_table in Hfe.
  destruct (String.eqb f "transfer"), (String.eqb f "transfer_exc0"), (String.eqb f "transfer_exc1"); discriminate.
Qed.

Lemma gen_table_total : forall f pre post vs sigma,
  gen_table f = Some (FunSpecS pre post) ->
  pre sigma vs ->
  exists r ups, post sigma vs r ups /\ updates_dom_in sigma ups.
Proof.
  intros f pre post vs sigma Hfe Hpre. unfold gen_table in Hfe.
  destruct (String.eqb f "transfer") eqn:E,
           (String.eqb f "transfer_exc0") eqn:E2,
           (String.eqb f "transfer_exc1") eqn:E3;
    try discriminate.
  all: try solve [injection Hfe as Heq; subst pre post; destruct Hpre as [source_id [target_id [order [amount [store_d [balance_source_id [currency_source_id [balance_target_id [currency_target_id [Hvs [Hcell [Hlook_source_id [Hlook_target_id [Hsc Havail]]]]]]]]]]]]]]; exists (RVal (LitInt balance_source_id)), [(store_loc, LitDict (dict_insert_str target_id (row_of (balance_target_id + amount) (currency_target_id)) (dict_insert_str source_id (row_of (balance_source_id - amount) (currency_source_id)) store_d)))]; split; [exists source_id, target_id, order, amount, store_d, balance_source_id, currency_source_id, balance_target_id, currency_target_id; repeat split; auto | unfold updates_dom_in; constructor; [|constructor]; simpl; rewrite Hcell; eexists; reflexivity]].
  all: try solve [injection Hfe as Heq; subst pre post; destruct Hpre as [source_id [target_id [order [amount [store_d [balance_source_id [currency_source_id [balance_target_id [currency_target_id [Hvs [Hcell [Hlook_source_id [Hlook_target_id Hwhen]]]]]]]]]]]]]; exists (RExn "InsufficientFundsError" (LitTuple [LitString source_id; LitInt amount])), []; split; [exists source_id, target_id, order, amount, store_d, balance_source_id, currency_source_id, balance_target_id, currency_target_id; repeat split; auto | unfold updates_dom_in; constructor]].
  all: try solve [injection Hfe as Heq; subst pre post; destruct Hpre as [source_id [target_id [order [amount [store_d [balance_source_id [currency_source_id [balance_target_id [currency_target_id [Hvs [Hcell [Hlook_source_id [Hlook_target_id Hwhen]]]]]]]]]]]]]; exists (RExn "CurrencyMismatchError" (LitTuple [LitString source_id; LitString target_id])), []; split; [exists source_id, target_id, order, amount, store_d, balance_source_id, currency_source_id, balance_target_id, currency_target_id; repeat split; auto | unfold updates_dom_in; constructor]].
Qed.

#[global] Instance gen_fun_ctx : FunCtx :=
  {| fun_entries := gen_table;
     fun_specs_total := gen_table_total_pure;
     fun_specsS_total := gen_table_total |}.

End gen_transfer.